### ISSUE TITLE
Thanks for plane-fitting least square point

### ISSUE THREAD

**Issue by p0nce** [emilk/blog#8]
Hello,

I'm successfully using your least-square method, thanks for that!
https://github.com/AuburnSounds/Dplug/issues/580

In this case we extract normal from an axis-aligned depth map, so the final code is surprisingly quick:
https://github.com/AuburnSounds/Dplug/blob/master/gui/dplug/gui/ransac.d#L48

So it is a "thank you" issue since our former non-linear method was a lot slower, and worse-looking!
It would be nice to have licensing information (or your permission) for inclusion.

**Comment by emilk** [comment]
You're welcome!

A source code attribution (like you have) is good enough for me!
